### ISSUE TITLE
Implement ```autodistill-yolov6```

### ISSUE THREAD

**Issue by bazylhorsey** [autodistill/autodistill#65]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Description

With the recent release of Yolov6v3, I'd like to submit a PR for hacktoberfest with my team implementing this model.

Yolov6v3 is implemented in ultralytics, so the change shouldn't be too different than YoloNAS.

If anyone has any considerations before implementation would love to start a conversation, or perhaps an intro meeting to get acquainted. 

### Use case

Autodistill can be used alongside Yolov6 to go dataset->model like other model implementations.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by capjamesg** [comment]
Hello there! I have added the `hacktoberfest` label to this task. We would love to have YOLOv6 available in the ecosystem!

Regarding implementation, please fork the [Autodistill base model template](https://github.com/autodistill/autodistill-base-model-template) and follow the instructions in the README. These instructions cover how to implement and document the package.

I'm happy to meet for 15 minutes tomorrow if there are any pending questions (email me at james [at] roboflow [dot] com)! I am in the UK so I may not respond until tomorrow morning (it is 8pm here now). Otherwise, I'll be here to review your code when you are ready!

**Comment by capjamesg** [comment]
Apologies, I meant to link to the [target model template](https://github.com/autodistill/autodistill-target-model-template).

**Comment by bazylhorsey** [comment]
https://github.com/ArvistDev/autodistill-yolov6

while implementing I noticed there are no differences between Yolov8 and Yolov6. @capjamesg I think it'd be better if we made a single yolo repo that had support for everything included in ultralytics so that we can consolidate support.

**Comment by yeldarby** [comment]
I think it's probably better to keep them separate given the canonical [YOLOv4](https://github.com/AlexeyAB/darknet), [YOLOv6](https://github.com/meituan/YOLOv6), and [YOLOv7](https://github.com/WongKinYiu/yolov7) (along with others like [YOLOR](https://github.com/WongKinYiu/yolor) and [YOLOX](https://github.com/Megvii-BaseDetection/YOLOX)) are not Ultralytics models.

I could see having an `autodistill-ultralytics` that worked with multiple models they support though.

**Comment by capjamesg** [comment]
Great work @bazylhorsey!

Would you mind updating your README to have instructions on how to get started? You can copy the README_EXAMPLE.md file into README.md and replace any mentions of "CLIP" (the model in the template) with YOLOv6 and add the appropriate text to the introduction.

Regarding the model architectures, let's keep the models separate for now. It is probably best for us to consolidate Ultralytics models at some point into `autodistill-ultralytics`, but we need to think about how that API will look. Will you do `from autodistill_ultralytics import Ultralytics` then initailize a model like `model = Ultralytics(ontology, model_architecture="yolov8")`?

When you are ready with your README, we can publish the package under `autodistill-yololov6` on PyPi. Make sure you add your name / organization in there (put it in the intro if you'd like!) so that it is clear you contributed the model. You can also file a PR to this repository (`autodistill`) and add your model to the model matrix following the instructions in https://github.com/autodistill/autodistill/tree/main/automation. Feel free to add docs in the `docs` folder, too!

When the package is live, I can announce it on my LinkedIn and tag you if you'd like (if so, please share a link to your profile).

**Comment by capjamesg** [comment]
I am going to close this since Hacktoberfest is almost over. Feel free to continue commenting here @bazylhorsey re: what I said above, then we can announce the extension!
